### ISSUE TITLE
Error creating the environment

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/simulation-fourier-reconstruction#3]
## Summary
While running `conda env create -f environment.yml`, I got an error stating that it cannot find `jupyter_bokeh`.

![Screen Shot 2021-06-07 at 18 21 17](https://user-images.githubusercontent.com/47249340/121094931-61e3d680-c7bd-11eb-9567-ddf066fda3e3.png)

## Reproduction steps:
git clone https://github.com/shimming-toolbox/simulation-fourier-reconstruction.git
cd simulation-fourier-reconstruction
checkout gc/jupyter-notebook
conda env create -f environment.yml

## Notes
I do have miniconda installed
I'm on MacOS BigSur

**Comment by gaspardcereza** [comment]
@po09i I changed the install of Jupyter Bokeh from conda to pip and didn't notice any problem locally. I also tried on Binder and it worked.

Could you try it on your end if you have a few minutes ? 

Btw: Binder does not seem to like the images being in a separate folder (took a long time to set up the env)...

**Comment by po09i** [comment]
Environment installation is working as of https://github.com/shimming-toolbox/simulation-fourier-reconstruction/pull/2/commits/2cf5b5cfdc11d03e2b89aea31ac5171e323348c0 👌
